apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: nginx-satya
    image: nginx:1.20.1
    ports:
    - containerPort: 80
  - name: watcher-satya
    image: afakharany/watcher:latest
    ports:
    - containerPort: 8080
